const { createGlobalStyle } = require('styled-components');

export const GlobalStyle = createGlobalStyle`

*{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}

html{
    font-size: 62.5%;
}

body{
    font-size: 1.4rem;
    background: rgba(240,240,240,1);
}

ul,li{
    padding:0;
    margin:0;
    box-sizing: border-box;
    list-style-type: none;
}

  
  a{
    text-decoration: none;
  }
  
  
  img{
    display: inline-block;
    max-width: 100%;
  }

  .video-preview-modal{
    position: fixed;
    inset: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 999999999999999999999999999999999999999999;
    .mark{
        position: absolute;
        inset: 0;
        background: rgba(0,0,0,0.3);
        
    }
    video{
        z-index: 1;
    }
    .anticon-close{
        position: absolute;
        right: 40px;
        color: white;
        top: 30px;
        font-size: 30px;
    }

}
  
  .section-title{
    padding: 1rem 0;
    font-size: 1.6rem;
    font-weight: 600;
    opacity: .6;
    text-transform: uppercase;
}

.box-shadow{
    -webkit-box-shadow:0px 0px 10px 4px rgba(62,66,66,0.05);
-moz-box-shadow: 0px 0px 10px 4px rgba(62,66,66,0.05);
box-shadow: 0px 0px 10px 4px rgba(62,66,66,0.05);
}


.ant-modal-wrap{
    z-index:1000000;
}
.ant-message{
    
    z-index:1000000;
}

.ant-btn-primary{
    background: ${(style)=>style.theme.blueClr};
    border-color: ${(style)=>style.theme.blueClr};
}

.ant-btn-primary[disabled]{
    background: #1890ff8c;
    color: white;   
    &:hover{
        background: #1890ff8c;
    color: white;  
    }
}

.username{
    color: ${(style)=>style.theme.headingTextClr};
    font-size: 1.6rem;
    font-weight: 600;   
}
.ant-select-dropdown{
    z-index:9999999999999999999;
}

.q-button{
    border-radius: 10px;
    &.button-primary{
    }
    &.button-outline{
}
}
.new-post-modal{
    .ant-modal-header{
        .ant-modal-title{
            font-size: 2rem;
            font-weight: 700;

        }
        text-align: center;
    }
    
    .ant-modal-footer{
        button{
            width: 100%;
        } 
            
    }

    .ant-modal-body{
        padding: 1rem;
    }
    .scope{
        
        .ant-select-selector{
            &:hover,.ant-select-focused{
                border: thin solid transparent;
                box-shadow: none;
            }
            border-radius: 5px;
            background: #E4E6EB;
            .ant-select-selection-item{
            font-weight: 500;
                font-size: 1.3rem;
            }

        }
    }

    
    
    label[for="post-content"]{
        height: 300px;
        font-size: 1.9rem;
        display:inline-block;
        width: 100%;
        margin-bottom:1rem;
        
        p{
            position: relative;
            text-align: center;
            top:50%;
            transform: translateY(-50%);
            
            &::after{
                content: "|";
                animation: myText .5s  infinite alternate; 
                visibility: hidden;
            }
            
            
        }
    }
    
    #post-content:focus + label[for="post-content"]{
        p{
            padding: 1rem;
            &::after{
                visibility: visible;
            }
        }
    }

    .content{
        margin: 1rem 0;
        width: 100%;
        font-size: 1.9rem;
        outline: none;
        border-color: transparent;
        box-shadow: none;
        &:hover{
            border-color: transparent;
            box-shadow: none;
            outline: none;

        }
    }

    .hide-input{
        margin: 0 !important;
        outline: none;
        border-color: transparent;
        box-shadow: none;
        width: 0;
        height:0;
        
    }

    .ant-radio-button-wrapper{
        padding: 0;
    }
    .ant-radio-button-wrapper + .ant-radio-button-wrapper{
        margin-left: 1rem;

    }

    svg{
        cursor: pointer;
    }
}

.ant-image-preview-mask{
    z-index: 99999999;
}
.ant-image-preview-wrap{
    z-index: 999999990;

}

@keyframes myText {
    from {opacity:0}
    to {opacity:1}
  }



}
.scale-up-center {
	-webkit-animation: scale-up-center 0.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: scale-up-center 0.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-6-5 16:37:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}


`;
